// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASGqAi7ZfrSpkbgTyN0ddB6cF0cZTD0OY',
    appId: '1:64246944264:web:b5e78032e4aa275903f7bd',
    messagingSenderId: '64246944264',
    projectId: 'reecaiptscanner',
    authDomain: 'reecaiptscanner.firebaseapp.com',
    storageBucket: 'reecaiptscanner.firebasestorage.app',
    measurementId: 'G-YJZ0CRD3TG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPIBECw4eDsKMom4L1bNI3PtUGq7HnUw',
    appId: '1:64246944264:ios:c6c8bb00c4b8977703f7bd',
    messagingSenderId: '64246944264',
    projectId: 'reecaiptscanner',
    storageBucket: 'reecaiptscanner.firebasestorage.app',
    iosClientId: '64246944264-uj8r7oket7nqldasv15sjg8uave9knnr.apps.googleusercontent.com',
    iosBundleId: 'com.ibrahim.receiptscanner',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76A7yEDY_p583pNLQNXyChHBnblZaf5o',
    appId: '1:64246944264:android:b52e79a302b44fe903f7bd',
    messagingSenderId: '64246944264',
    projectId: 'reecaiptscanner',
    storageBucket: 'reecaiptscanner.firebasestorage.app',
  );

}